"@generated by @aspect_rules_js//npm/private:npm_translate_lock.bzl from //:pnpm-lock.yaml"

load("@aspect_rules_js//npm:npm_import.bzl", "npm_import")

def npm_repositories():
    "Generated npm_import repository rules corresponding to npm packages in //:pnpm-lock.yaml"
    npm_import(
        name = "npm__js-tokens__4.0.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "js-tokens",
        version = "4.0.0",
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz",
        lifecycle_hooks_no_sandbox = True,
        npm_translate_lock_repo = "npm",
        integrity = "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==",
        transitive_closure = {
            "js-tokens": ["4.0.0"],
        },
    )

    npm_import(
        name = "npm__loose-envify__1.4.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "loose-envify",
        version = "1.4.0",
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz",
        lifecycle_hooks_no_sandbox = True,
        npm_translate_lock_repo = "npm",
        integrity = "sha512-lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==",
        deps = {
            "js-tokens": "4.0.0",
        },
        transitive_closure = {
            "loose-envify": ["1.4.0"],
            "js-tokens": ["4.0.0"],
        },
    )

    npm_import(
        name = "npm__react-dom__18.2.0__react_18.2.0",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "packages/frontend": ["react-dom"],
        },
        package = "react-dom",
        version = "18.2.0_react@18.2.0",
        url = "https://registry.npmjs.org/react-dom/-/react-dom-18.2.0.tgz",
        lifecycle_hooks_no_sandbox = True,
        npm_translate_lock_repo = "npm",
        integrity = "sha512-6IMTriUmvsjHUjNtEDudZfuDQUoWXVxKHhlEGSk81n4YFS+r/Kl99wXiwlVXtPBtJenozv2P+hxDsw9eA7Xo6g==",
        deps = {
            "loose-envify": "1.4.0",
            "react": "18.2.0",
            "scheduler": "0.23.0",
        },
        transitive_closure = {
            "react-dom": ["18.2.0_react@18.2.0"],
            "loose-envify": ["1.4.0"],
            "react": ["18.2.0"],
            "scheduler": ["0.23.0"],
            "js-tokens": ["4.0.0"],
        },
    )

    npm_import(
        name = "npm__react__18.2.0",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "packages/frontend": ["react"],
        },
        package = "react",
        version = "18.2.0",
        url = "https://registry.npmjs.org/react/-/react-18.2.0.tgz",
        lifecycle_hooks_no_sandbox = True,
        npm_translate_lock_repo = "npm",
        integrity = "sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==",
        deps = {
            "loose-envify": "1.4.0",
        },
        transitive_closure = {
            "react": ["18.2.0"],
            "loose-envify": ["1.4.0"],
            "js-tokens": ["4.0.0"],
        },
    )

    npm_import(
        name = "npm__scheduler__0.23.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "scheduler",
        version = "0.23.0",
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.23.0.tgz",
        lifecycle_hooks_no_sandbox = True,
        npm_translate_lock_repo = "npm",
        integrity = "sha512-CtuThmgHNg7zIZWAXi3AsyIzA3n4xx7aNyjwC2VJldO2LMVDhFK+63xGqq6CsJH4rTAt6/M+N4GhZiDYPx9eUw==",
        deps = {
            "loose-envify": "1.4.0",
        },
        transitive_closure = {
            "scheduler": ["0.23.0"],
            "loose-envify": ["1.4.0"],
            "js-tokens": ["4.0.0"],
        },
    )

    npm_import(
        name = "npm__typescript__4.9.3",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "packages/common": ["typescript"],
        },
        package = "typescript",
        version = "4.9.3",
        url = "https://registry.npmjs.org/typescript/-/typescript-4.9.3.tgz",
        lifecycle_hooks_no_sandbox = True,
        npm_translate_lock_repo = "npm",
        integrity = "sha512-CIfGzTelbKNEnLpLdGFgdyKhG23CKdKgQPOBc+OUNrkJ2vr+KSzsSV5kq5iWhEQbok+quxgGzrAtGWCyU7tHnA==",
        transitive_closure = {
            "typescript": ["4.9.3"],
        },
    )

    npm_import(
        name = "npm__typescript__4.9.4",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "packages/frontend": ["typescript"],
        },
        package = "typescript",
        version = "4.9.4",
        url = "https://registry.npmjs.org/typescript/-/typescript-4.9.4.tgz",
        lifecycle_hooks_no_sandbox = True,
        npm_translate_lock_repo = "npm",
        integrity = "sha512-Uz+dTXYzxXXbsFpM86Wh3dKCxrQqUcVMxwU54orwlJjOpO3ao8L7j5lH+dWfTwgCwIuM9GQ2kvVotzYJMXTBZg==",
        transitive_closure = {
            "typescript": ["4.9.4"],
        },
    )
